### ISSUE TITLE
$wgMatomo settings aren't working yet ($wgPiwik works)

### ISSUE THREAD

**Issue by devinplatt** [DaSchTour/matomo-mediawiki-extension#25] opened 2019-02-24 01:40 UTC
I just added this extension, and $wgMatomoURL and $wgMatomoIDSite didn't work. I got the "You need to set the settings for Matomo" message when viewing my wiki's page source.

Using $wgPiwikURL and $wgPiwikIDSite solved the problem. So this isn't critical, but it looks like the recent rename changes are still incomplete.

Thanks,
Devin

**Comment by kuality** [comment] 2019-02-26 23:27
I second that, still a problem. I downloaded the extension via composer if that makes any difference.

**Comment by Seb35** [comment] 2019-02-28 17:44
Indeed, and thanks for reporting. I reproduced the issue and will push the fix in some hours in a version 4.0.1.

There are in fact two bugs in the same place:
* the one reported here (I wrote Mamoto instead of Matomo in the code) and
* the params wgPiwik* should have precedence because wgMatomo* are always defined as default parameters (currently wgPiwik* are never used in this version 4.0.0).

**Comment by Seb35** [comment] 2019-02-28 19:27
Fixed in version 4.0.1. Thanks again for this bug report.

**Closed by Seb35** 2019-02-28 19:27 UTC
Labels: bug

**Comment by kuality** [comment] 2019-03-02 01:23
And thank you for the quick fix. Confirmed working.
