### ISSUE TITLE
Installation via Composer fails

### ISSUE THREAD

**Issue by kghbln** [DaSchTour/matomo-mediawiki-extension#21] opened 2018-01-10 16:37 UTC
## Setup
- MediaWiki | 1.27.4 (bc962b0)18:47, 5. Jan. 2018
- PHP | 5.6.33-0+deb8u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Piwik Integration | 3.0.0

## Issue
I am not sure this is still supported but if I install via Composer, the software get move into `/../extensions/PiwikiIntegration`. As soon as I add `wfLoadExtension( 'Piwik' );` the wiki starts to error due to a missing "extension.json" file which obviously was indeed available.

@Seb35 FYI

**Comment by Seb35** [comment] 2018-01-26 20:46
Just to say I saw this, I will try to reproduce and fix it. To answer your initial question: yes, Composer should be still supported.

**Comment by kghbln** [comment] 2018-01-26 21:33
No worries. There are other ways to get it up and running. So no pressing urgency.

**Comment by kghbln** [comment] 2018-01-31 22:53
@Seb35 Thanks for looking at this.

I believe the best is to switch to "Matomo" as the name and release this renamed one as 4.0.0 in a way that is easiest, i.e. as outlined in the issue linked.

**Comment by Seb35** [comment] 2018-02-01 08:10
In the same time, I would like to make this extension farm-compatible, which means remove the entry point Piwik.php (which is currenly autoloaded with Composer unconditionally and hence Piwik is unconditionally enabled on a whole farm) and make mandatory an explicit loading with wfLoadExtension, so that farms can decide during their LocalSettings.php-time if they want to enable Matomo for the current wiki.

As far as I know, only PageForms currently has such a configuration, but I find it is the best solution to use both Composer for installation+dependencies and MediaWiki for activation (farm-compatible).

With such a big change, I will first add a warning on top of its MediaWiki.org page to warn in advance of this rename + change of loading method.

**Comment by Seb35** [comment] 2018-02-01 08:26
Well, there are also all the parameters which could be renamed ($wgPiwikURL, etc.), or not. I’m enclined to rename them; it will be still a bigger change to be properly documented, but the work will be more coherent if done in bulk than spend months to rename it part by part, and I guess the situation would be confused when users request help on support desk. Obviously old parameters will continue to work; possibly a deprecation warning could be issued.

**Comment by kghbln** [comment] 2018-02-01 09:14
> In the same time, I would like to make this extension farm-compatible, ...

Great idea. There are other extensions that do this too like Mermaid, Semantic Glossary etc.

> Well, there are also all the parameters which could be renamed ($wgPiwikURL, etc.)

+2 Another reason for moving to a 4.0.0 Indeed this has to be documented visibly.

**Comment by Seb35** [comment] 2018-02-01 14:04
In the commits 7ac05fb and b182144 there are most of the changes, it should be checked before merged. And merged only when proper communication and documentation on MediaWiki.org page will be done.

Also I didn’t change the file names `piwik.js` and `piwik.php` given they are still in the master version of Matomo; possibly advice from official developers should be searched about this.

**Comment by Seb35** [comment] 2018-02-01 14:47
I put a warning on top of [mw:Extension:Piwik Integration](https://www.mediawiki.org/wiki/Extension:Piwik_Integration) and will push the change in March to reduce a bit the surprise effect amongst sysadmins doing upgrades.

**Comment by Seb35** [comment] 2019-02-15 14:14
Sorry for being so long in doing this rename.

@DaSchTour Could you rename this repository to "matomo-mediawiki-extension"? (GitHub will create a redirect from the old name)

As well as mark the package on Packagist as Abandonned? ([procedure here](https://github.com/composer/packagist/issues/47#issuecomment-271962248))

**Comment by DaSchTour** [comment] 2019-02-19 08:37
Okay. I changed the repository name. But I have no idea how packagist works and I can't find the piwik extension on packagist.

**Comment by DaSchTour** [comment] 2019-02-19 08:40
I hope it's all correct now

**Comment by Seb35** [comment] 2019-02-20 08:42
I cannot myself add the new package mediawiki/matomo on packagist, I have the error message
> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at mediawiki

@DaSchTour Can you add me as maintainer on Packagist of mediawiki/piwik-integration (I’m seb35 there) and as admin on this GitHub repo? I hope to be able to manage then.

**Comment by DaSchTour** [comment] 2019-02-20 08:49
I added you as a maintainer. You are already collaborator for this repo. I don't see that there are any possibilities to give you more rights.

**Comment by Seb35** [comment] 2019-02-20 11:32
Thanks for Packagist, I created the new package [mediawiki/matomo](https://packagist.org/packages/mediawiki/matomo) and it works both when installed with Composer and as a standalone extension, but in both cases it needs to be explicitely activated with `wfLoadExtension( 'Matomo' );`.

If you could add me add as admin on GitHub in the repo Settings > Collaborators and teams > Collaborators > Seb35 > dropdown 'write' to be changed to 'admin'.

**Comment by DaSchTour** [comment] 2019-02-25 08:00
There is no such setting. Is it possible that this is only available for organization repos or paid accounts?

**Comment by Seb35** [comment] 2019-02-28 16:55
Ok, I see also this behaviour on a repo belonging to me. I tested previously on an organisation repo, indeed.

So, sorry requesting so much things, I expect this one is the last one: could you connect yourself to Packagist through GitHub (I defined you as co-maintainer of the package mediawiki/matomo) to allow Packagist to auto-update the repo after push? Or define the webhook in the GitHub repo with a Packagist key available in your Packagist account. The process is explained [here](https://packagist.org/about#how-to-update-packages).

**Comment by samwilson** [comment] 2021-12-08 23:53
This seems to be complete now, is that right? I've been able to install and run the `mediawiki/matomo` package without problems.

**Comment by Seb35** [comment] 2023-10-27 18:48
I cannot configure Packagist to auto-update after a new Github release, but it’s not that important, I just have to click a button on Packagist to manually update it.

Anyway I just issued a new version of this extension, and Packagist now has this version 5.0.0.

**Closed by Seb35** 2023-10-27 18:48 UTC
